DROP TABLE IF EXISTS stg_ae_raw;

CREATE TABLE stg_ae_raw (
    file_month                          VARCHAR(20),
    financial_year                      VARCHAR(10),
    org_code                            VARCHAR(20),
    region                              VARCHAR(100),
    org_name                            VARCHAR(200),
    type1_attendances                   VARCHAR(20),
    type2_attendances                   VARCHAR(20),
    type3_attendances                   VARCHAR(20),
    total_attendances                   VARCHAR(20),
    type1_under4hr                      VARCHAR(20),
    type2_under4hr                      VARCHAR(20),
    type3_under4hr                      VARCHAR(20),
    total_under4hr                      VARCHAR(20),
    type1_over4hr                       VARCHAR(20),
    type2_over4hr                       VARCHAR(20),
    type3_over4hr                       VARCHAR(20),
    total_over4hr                       VARCHAR(20),
    pct_within4hr_all                   VARCHAR(20),
    pct_within4hr_type1                 VARCHAR(20),
    pct_within4hr_type2                 VARCHAR(20),
    pct_within4hr_type3                 VARCHAR(20),
    emergency_admissions_type1          VARCHAR(20),
    emergency_admissions_type2          VARCHAR(20),
    emergency_admissions_type3          VARCHAR(20),
    total_emergency_admissions_via_ae   VARCHAR(20),
    other_emergency_admissions          VARCHAR(20),
    total_emergency_admissions          VARCHAR(20),
    over4hr_decision_to_admit           VARCHAR(20),
    over12hr_decision_to_admit          VARCHAR(20),
    loaded_at                           TIMESTAMP DEFAULT NOW()
);