CREATE TABLE fact_ae_monthly (
    id                                  SERIAL PRIMARY KEY,
    period_date                         DATE NOT NULL,
    financial_year                      VARCHAR(10) NOT NULL,
    financial_quarter                   VARCHAR(5) NOT NULL,
    org_code                            VARCHAR(20) NOT NULL,
    org_name                            VARCHAR(200),
    region                              VARCHAR(100),
    type1_attendances                   INTEGER,
    type2_attendances                   INTEGER,
    type3_attendances                   INTEGER,
    total_attendances                   INTEGER,
    type1_under4hr                      INTEGER,
    type2_under4hr                      INTEGER,
    type3_under4hr                      INTEGER,
    total_under4hr                      INTEGER,
    type1_over4hr                       INTEGER,
    type2_over4hr                       INTEGER,
    type3_over4hr                       INTEGER,
    total_over4hr                       INTEGER,
    pct_within4hr_all                   DECIMAL(8,6),
    pct_within4hr_type1                 DECIMAL(8,6),
    pct_within4hr_type2                 DECIMAL(8,6),
    pct_within4hr_type3                 DECIMAL(8,6),
    emergency_admissions_type1          INTEGER,
    emergency_admissions_type2          INTEGER,
    emergency_admissions_type3          INTEGER,
    total_emergency_admissions_via_ae   INTEGER,
    other_emergency_admissions          INTEGER,
    total_emergency_admissions          INTEGER,
    over4hr_decision_to_admit           INTEGER,
    over12hr_decision_to_admit          INTEGER,
    breach_rate_pct                     DECIMAL(6,2),
    is_suppressed                       BOOLEAN DEFAULT FALSE
);